name: Check

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  check-all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libzstd-dev libopencv-dev
        echo 1.23.2>mongodb/mongo-c-driver/VERSION_CURRENT

    - name: Build
      run: |
        make
        pushd modules/nemc_helper
        make
        popd
        pushd modules/products
        make
        popd
        pushd modules/shutdown
        make
        popd
        pushd modules/whitelist
        make
        popd
        pushd modules/user_center
        make
        popd

