name: Check

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  check-all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libzstd-dev libopencv-dev
        echo 1.23.2>mongodb/mongo-c-driver/VERSION_CURRENT

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j8
    - name: Pack artifacts
      run: tar -czf pv4-prod-dry.tar.gz pv4 modules.json prod_modules
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pv4-prod-dry
        path: pv4-prod-dry.tar.gz
